import { Rajdhani, Work_Sans } from 'next/font/google';
import { ReactNode } from 'react';

import AuthListener from '@/components/AuthListener';
import './globals.css';
import Header from '@/components/Header';

import Provider from './Providers';

const rajdhani = Rajdhani({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-rajdani',
  style: ['normal'],
});

const worksans = Work_Sans({
  subsets: ['latin'],
  variable: '--font-worksans',
  style: ['normal', 'italic'],
});

export const metadata = {
  title: 'GameStack - Your personalized backlog tracker',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en'>
      <body className={`${rajdhani.className} ${worksans.className} pb-20`}>
        <div id='modal'></div>
        <Provider>
          <AuthListener />
          <div className='container mx-auto px-5'>
            <Header />
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
