import { Rajdhani, Work_Sans } from 'next/font/google';
import AuthListener from '@/components/AuthListener';
import './globals.css';
import Provider from './Providers';
import Header from '@/components/Header';

const rajdhani = Rajdhani({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-rajdani',
  styles: ['normal', 'italic', 'bold', 'semibold'],
});

const worksans = Work_Sans({
  subsets: ['latin'],
  variable: '--font-worksans',
  styles: ['normal', 'italic', 'bold', 'semibold'],
});

export const metadata = {
  title: 'GameStack - Your personalized backlog tracker',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <div id='modal'></div>
        <Provider>
          <AuthListener />
          <div className='container mx-auto px-5'>
            <Header />
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
